### ISSUE TITLE
Image loading problem

### ISSUE THREAD

**Issue by dlsquared** [TheCherno/Cherno#4]
The error(project is not edited):

Exception in thread "main" java.lang.IllegalArgumentException: input == null!
    at javax.imageio.ImageIO.read(Unknown Source)
    at com.thecherno.cherno.engine.graphics.Texture.load(Texture.java:23)
    at com.thecherno.cherno.Main.init(Main.java:20)
    at com.thecherno.cherno.Main.main(Main.java:42)

**Comment by ghost** [comment]
The issue has been reported and fixed by Orangejuice724 in ticket #3 
https://github.com/Orangejuice724/Cherno/commit/3cd41cf9175a038bd936ded3948d3375578169db
